/**
 * Workspace/progress artifact utilities for the Harness extension.
 *
 * Separates run tracking, progress logging, and workflow script generation
 * from the main execution flow. Git safety (workspace isolation, project root
 * resolution) is delegated to ./gitSafety.js — this module re-exports those
 * types and functions for backward compatibility.
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync, appendFileSync } from "node:fs";
import { join } from "node:path";
import type { AgentSession } from "@earendil-works/pi-coding-agent";
import { getLastAssistantText, type Sprint, type SprintResult } from "./parsing.js";
import {
	resolveProjectRoot,
	createHarnessWorkspace,
	type HarnessWorkspace,
} from "./gitSafety.js";

// Re-export git safety types and functions for callers that import from artifacts.
export { resolveProjectRoot, createHarnessWorkspace, type HarnessWorkspace };

// ─── Progress Artifacts ───────────────────────────────────────────────────────

/** Write or append to harness-run-local progress artifacts. */
export function writeProgress(runDir: string, sprintNum: number, title: string, passed: boolean, detail: string) {
	const progressPath = join(runDir, "PROGRESS.md");
	const line = [
		`## Sprint ${sprintNum}: ${title}`,
		`**Status**: ${passed ? "[✓] PASS" : "[x] FAIL"}`,
		`**Detail**: ${detail.slice(0, 200)}`,
		`**Time**: ${new Date().toISOString()}`,
		"",
	].join("\n");
	if (!existsSync(progressPath)) {
		writeFileSync(progressPath, `# Harness Build Progress\n\nStarted: ${new Date().toISOString()}\n\n${line}`);
	} else {
		appendFileSync(progressPath, line);
	}

	const sprintStatePath = join(runDir, `sprint-${sprintNum}-state.json`);
	const stateJson = {
		id: `sprint-${sprintNum}`,
		title,
		status: passed ? "passed" : "failed",
		detail: detail.slice(0, 1000),
		completedAt: new Date().toISOString(),
		gates: { "review-passed": passed },
	};
	writeFileSync(sprintStatePath, JSON.stringify(stateJson, null, 2), "utf-8");
}

// ─── Workflow Script Generation ───────────────────────────────────────────────

/** Generate a reusable workflow script at .pi/workflows/{slug}.mjs and a run card. */
export function generateWorkflowScript(
	cwd: string,
	prompt: string,
	specText: string,
	sprints: Sprint[],
	pattern: string,
	results: SprintResult[],
): string | null {
	try {
		// Generate a slug from the prompt
		const slug = prompt
			.toLowerCase()
			.replace(/[^a-z0-9]+/g, "-")
			.replace(/^-|-$/g, "")
			.slice(0, 40) || "harness-run";

		const workflowsDir = join(cwd, ".pi", "workflows");
		const runsDir = join(cwd, ".pi", "harness-runs");
		mkdirSync(workflowsDir, { recursive: true });
		mkdirSync(runsDir, { recursive: true });

		// Write workflow script
		const script = `// Generated by Harness — re-run with: node .pi/workflows/${slug}.mjs
// Original prompt: ${JSON.stringify(prompt)}

import { createAgentSession, SessionManager } from "@earendil-works/pi-coding-agent";
import { getModel } from "@earendil-works/pi-ai";

const CWD = process.cwd();
const MODEL = getModel("anthropic", "claude-sonnet-4-20250514");

const sprints = ${JSON.stringify(sprints, null, 2)};

async function run() {
	console.log("Running harness workflow: ${slug}");
	console.log("Pattern: ${pattern}");
	console.log("Sprints: " + sprints.length + "\\n");

	for (const sprint of sprints) {
		console.log("\\n=== Sprint " + sprint.number + ": " + sprint.title + " ===");
		const { session: gen } = await createAgentSession({
			model: MODEL,
			tools: ["read", "bash", "edit", "write", "grep", "find", "ls"],
			sessionManager: SessionManager.inMemory(CWD),
			cwd: CWD,
		});
		await gen.prompt("Implement: " + sprint.title + "\\n" + sprint.description);
		gen.dispose();
	}
	console.log("\\nDone.");
}
run().catch(console.error);
`;
		writeFileSync(join(workflowsDir, `${slug}.mjs`), script, "utf-8");

		// Write harness run card from template
		const templatePath = join(cwd, ".pi", "templates", "harness-card.md");
		const allPassed = results.every((r) => r.passed);
		let card: string;

		if (existsSync(templatePath)) {
			const template = readFileSync(templatePath, "utf-8");
			const sprintSummary = results
				.map((r, i) => `| ${i + 1} | ${r.sprint} | ${r.passed ? "PASS" : "FAIL"} | ${r.iterations} |`)
				.join("\\n");
			card = template
				.replace(/\*\*Name:\*\*.*/m, `**Name:** ${slug}`)
				.replace(/\*\*Date:\*\*.*/m, `**Date:** ${new Date().toISOString()}`)
				.replace(/\*\*Change.*\*\*.*/m, `**Change / workflow under test:** ${prompt}`)
				.replace(/Run report path:.*/, `Run report path: .pi/harness-runs/${slug}.md`)
				.replace(/Subagent output files:.*/, `Subagent output files: .pi/workflows/${slug}.mjs`);
			card += `\\n### Results\\n| Sprint | Title | Result | Iterations |\\n|--------|-------|--------|------------|\\n${sprintSummary}`;
			card += `\\n**Status**: ${allPassed ? "All passed" : "Some failed"}`;
		} else {
			card = `# Harness Run: ${slug}\\n**Prompt**: ${prompt}\\n**Date**: ${new Date().toISOString()}\\n**Status**: ${allPassed ? "All passed" : "Some failed"}`;
		}

		writeFileSync(join(runsDir, `${slug}.md`), card, "utf-8");
		return slug;
	} catch {
		return null;
	}
}

// ─── Run Tracker ───────────────────────────────────────────────────────────────

/**
 * Tracks all agent conversations and artifacts for a harness run.
 * Stores everything under .pi/harness-runs/<run-id>/ organized by sprint.
 */
export class HarnessTracker {
	readonly runDir: string;
	private startedAt = Date.now();
	private phaseLog: Array<{ phase: string; startedAt: number; agent: string }> = [];

	constructor(cwd: string, prompt: string) {
		const slug = prompt
			.toLowerCase()
			.replace(/[^a-z0-9]+/g, "-")
			.replace(/^-|-$/g, "")
			.slice(0, 30) || "harness";
		const timestamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
		this.runDir = join(cwd, ".pi", "harness-runs", `${timestamp}-${slug}`);
		try {
			mkdirSync(this.runDir, { recursive: true });
		} catch {
			// fail silently — tracking is best-effort
		}
	}

	private write(name: string, content: string) {
		try {
			writeFileSync(join(this.runDir, name), content, "utf-8");
		} catch {
			// best-effort
		}
	}

	private writeJSON(name: string, data: unknown) {
		this.write(name, JSON.stringify(data, null, 2));
	}

	startPhase(phase: string, agent: string) {
		this.phaseLog.push({ phase, startedAt: Date.now(), agent });
	}

	/** Save a full agent session transcript after prompt completes. */
	saveSession(subDir: string, role: string, session: AgentSession, systemPrompt: string) {
		const dir = join(this.runDir, subDir);
		try {
			mkdirSync(dir, { recursive: true });
		} catch {
			return;
		}

		// Write system prompt used
		writeFileSync(join(dir, `${role}-system-prompt.txt`), systemPrompt, "utf-8");

		// Write full conversation transcript
		const transcript = session.messages.map((m: any) => ({
			role: m.role,
			timestamp: m.timestamp,
			content: typeof m.content === "string" ? m.content : JSON.stringify(m.content),
			toolName: m.toolName,
			toolCallId: m.toolCallId,
		}) as any);
		this.writeJSON(`${subDir}/${role}-conversation.json`, transcript);

		// Write last assistant output as readable text
		const lastText = getLastAssistantText(session);
		if (lastText) {
			writeFileSync(join(dir, `${role}-output.txt`), lastText, "utf-8");
		}

		// Write usage summary
		let totalInput = 0,
			totalOutput = 0,
			totalCost = 0;
		for (const m of session.messages as any[]) {
			if (m.usage) {
				totalInput += m.usage.input || 0;
				totalOutput += m.usage.output || 0;
				totalCost += m.usage.cost?.total || 0;
			}
		}
		this.writeJSON(`${subDir}/${role}-usage.json`, {
			inputTokens: totalInput,
			outputTokens: totalOutput,
			totalCost: Math.round(totalCost * 10000) / 10000,
			turns: session.messages.filter((m: any) => m.role === "assistant").length,
		});
	}

	/** Write the spec from the planner. */
	saveSpec(specText: string) {
		this.write("spec.md", specText);
	}

	/** Write final build report. */
	saveReport(report: string) {
		this.write("build-report.md", report);
	}

	/** Write harness workspace/isolation metadata. */
	saveWorkspace(workspace: HarnessWorkspace) {
		this.writeJSON("workspace.json", workspace);
	}

	/** Write timing summary. */
	saveTiming() {
		const elapsed = ((Date.now() - this.startedAt) / 1000).toFixed(1);
		const phases = this.phaseLog.map((p) => ({
			phase: p.phase,
			agent: p.agent,
			durationMs: Date.now() - p.startedAt,
		}));
		this.writeJSON("timing.json", { totalSeconds: Number(elapsed), phases });
	}
}
