/**
 * Workspace/progress artifact utilities for the Harness extension.
 *
 * Separates run tracking, progress logging, and workflow script generation
 * from the main execution flow. Git safety (workspace isolation, project root
 * resolution) is delegated to ./gitSafety.js — this module re-exports those
 * types and functions for backward compatibility.
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync, appendFileSync } from "node:fs";
import { basename, join } from "node:path";
import type { AgentSession, AgentSessionEvent } from "@earendil-works/pi-coding-agent";
import { extractText, getLastAssistantText, type Sprint, type SprintResult } from "./parsing.js";
import {
	resolveProjectRoot,
	createHarnessWorkspace,
	type HarnessWorkspace,
} from "./gitSafety.js";

// Re-export git safety types and functions for callers that import from artifacts.
export { resolveProjectRoot, createHarnessWorkspace, type HarnessWorkspace };

// ─── Progress Artifacts ───────────────────────────────────────────────────────

/** Write or append to harness-run-local progress artifacts. */
export function writeProgress(runDir: string, sprintNum: number, title: string, passed: boolean, detail: string) {
	const progressPath = join(runDir, "PROGRESS.md");
	const line = [
		`## Sprint ${sprintNum}: ${title}`,
		`**Status**: ${passed ? "[✓] PASS" : "[x] FAIL"}`,
		`**Detail**: ${detail.slice(0, 200)}`,
		`**Time**: ${new Date().toISOString()}`,
		"",
	].join("\n");
	if (!existsSync(progressPath)) {
		writeFileSync(progressPath, `# Harness Build Progress\n\nStarted: ${new Date().toISOString()}\n\n${line}`);
	} else {
		appendFileSync(progressPath, line);
	}

	const sprintStatePath = join(runDir, `sprint-${sprintNum}-state.json`);
	const stateJson = {
		id: `sprint-${sprintNum}`,
		title,
		status: passed ? "passed" : "failed",
		detail: detail.slice(0, 1000),
		completedAt: new Date().toISOString(),
		gates: { "review-passed": passed },
	};
	writeFileSync(sprintStatePath, JSON.stringify(stateJson, null, 2), "utf-8");
}

// ─── Workflow Script Generation ───────────────────────────────────────────────

/** Generate a reusable workflow script at .pi/workflows/{slug}.mjs and a run card. */
export function generateWorkflowScript(
	cwd: string,
	prompt: string,
	specText: string,
	sprints: Sprint[],
	pattern: string,
	results: SprintResult[],
): string | null {
	try {
		// Generate a slug from the prompt
		const slug = prompt
			.toLowerCase()
			.replace(/[^a-z0-9]+/g, "-")
			.replace(/^-|-$/g, "")
			.slice(0, 40) || "harness-run";

		const workflowsDir = join(cwd, ".pi", "workflows");
		const runsDir = join(cwd, ".pi", "harness-runs");
		mkdirSync(workflowsDir, { recursive: true });
		mkdirSync(runsDir, { recursive: true });

		// Write a faithful manifest instead of a misleading replay script with hardcoded models/tools.
		const script = `// Generated by Harness as a reviewable run manifest.
// Original prompt: ${JSON.stringify(prompt)}
// This file intentionally does not auto-replay the run; use the harness tool with the same prompt and parameters.

export const harnessRun = ${JSON.stringify({ prompt, pattern, sprints, results }, null, 2)};

if (import.meta.url === \`file://\${process.argv[1]}\`) {
	console.log(JSON.stringify(harnessRun, null, 2));
}
`;
		writeFileSync(join(workflowsDir, `${slug}.mjs`), script, "utf-8");

		// Write harness run card from template
		const templatePath = join(cwd, ".pi", "templates", "harness-card.md");
		const allPassed = results.every((r) => r.passed);
		let card: string;

		if (existsSync(templatePath)) {
			const template = readFileSync(templatePath, "utf-8");
			const sprintSummary = results
				.map((r, i) => `| ${i + 1} | ${r.sprint} | ${r.passed ? "PASS" : "FAIL"} | ${r.iterations} |`)
				.join("\n");
			card = template
				.replace(/\*\*Name:\*\*.*/m, `**Name:** ${slug}`)
				.replace(/\*\*Date:\*\*.*/m, `**Date:** ${new Date().toISOString()}`)
				.replace(/\*\*Change.*\*\*.*/m, `**Change / workflow under test:** ${prompt}`)
				.replace(/Run report path:.*/, `Run report path: .pi/harness-runs/${slug}.md`)
				.replace(/Subagent output files:.*/, `Subagent output files: .pi/workflows/${slug}.mjs`);
			card += `\n### Results\n| Sprint | Title | Result | Iterations |\n|--------|-------|--------|------------|\n${sprintSummary}`;
			card += `\n**Status**: ${allPassed ? "All passed" : "Some failed"}`;
		} else {
			card = `# Harness Run: ${slug}\n**Prompt**: ${prompt}\n**Date**: ${new Date().toISOString()}\n**Status**: ${allPassed ? "All passed" : "Some failed"}`;
		}

		writeFileSync(join(runsDir, `${slug}.md`), card, "utf-8");
		return slug;
	} catch {
		return null;
	}
}

// ─── Run Tracker ───────────────────────────────────────────────────────────────

interface UsageSummary {
	inputTokens: number;
	outputTokens: number;
	cacheReadTokens: number;
	cacheWriteTokens: number;
	thinkingTokens: number;
	totalTokens: number;
	totalCost: number;
	turns: number;
}

interface UsageRecord extends UsageSummary {
	id: string;
	subDir: string;
	role: string;
}

type UnknownRecord = Record<string, unknown>;

function isRecord(value: unknown): value is UnknownRecord {
	return typeof value === "object" && value !== null;
}

function numberField(source: UnknownRecord, key: string): number {
	const value = source[key];
	return typeof value === "number" && Number.isFinite(value) ? value : 0;
}

function usageFromMessage(message: unknown): UsageSummary {
	const empty = {
		inputTokens: 0,
		outputTokens: 0,
		cacheReadTokens: 0,
		cacheWriteTokens: 0,
		thinkingTokens: 0,
		totalTokens: 0,
		totalCost: 0,
		turns: 0,
	};
	if (!isRecord(message) || !isRecord(message.usage)) return empty;

	const usage = message.usage;
	const cost = isRecord(usage.cost) ? numberField(usage.cost, "total") : 0;
	const input = numberField(usage, "input");
	const output = numberField(usage, "output");
	const cacheRead = numberField(usage, "cacheRead");
	const cacheWrite = numberField(usage, "cacheWrite");
	const thinking = numberField(usage, "thinking");
	const total = numberField(usage, "totalTokens") || input + output + cacheRead + cacheWrite + thinking;

	return {
		inputTokens: input,
		outputTokens: output,
		cacheReadTokens: cacheRead,
		cacheWriteTokens: cacheWrite,
		thinkingTokens: thinking,
		totalTokens: total,
		totalCost: cost,
		turns: 0,
	};
}

function summarizeSessionUsage(session: AgentSession): UsageSummary {
	const summary: UsageSummary = {
		inputTokens: 0,
		outputTokens: 0,
		cacheReadTokens: 0,
		cacheWriteTokens: 0,
		thinkingTokens: 0,
		totalTokens: 0,
		totalCost: 0,
		turns: 0,
	};

	for (const message of session.messages as readonly unknown[]) {
		if (isRecord(message) && message.role === "assistant") summary.turns++;
		const usage = usageFromMessage(message);
		summary.inputTokens += usage.inputTokens;
		summary.outputTokens += usage.outputTokens;
		summary.cacheReadTokens += usage.cacheReadTokens;
		summary.cacheWriteTokens += usage.cacheWriteTokens;
		summary.thinkingTokens += usage.thinkingTokens;
		summary.totalTokens += usage.totalTokens;
		summary.totalCost += usage.totalCost;
	}

	summary.totalCost = Math.round(summary.totalCost * 10000) / 10000;
	return summary;
}

function truncate(text: string, max = 4000): string {
	return text.length > max ? `${text.slice(0, max)}…` : text;
}

function safeJsonSummary(value: unknown, max = 4000): string {
	try {
		return truncate(JSON.stringify(value), max);
	} catch {
		return truncate(String(value), max);
	}
}

function eventPayload(event: AgentSessionEvent): UnknownRecord {
	switch (event.type) {
		case "tool_execution_start":
			return { event: event.type, toolName: event.toolName, toolCallId: event.toolCallId, args: safeJsonSummary(event.args) };
		case "tool_execution_update":
			return { event: event.type, toolName: event.toolName, toolCallId: event.toolCallId, args: safeJsonSummary(event.args), partialResult: safeJsonSummary(event.partialResult) };
		case "tool_execution_end":
			return { event: event.type, toolName: event.toolName, toolCallId: event.toolCallId, isError: event.isError, result: safeJsonSummary(event.result) };
		case "message_start":
		case "message_update":
			return isRecord(event.message) ? { event: event.type, messageRole: event.message.role } : { event: event.type };
		case "message_end":
			return isRecord(event.message)
				? { event: event.type, messageRole: event.message.role, text: "content" in event.message ? truncate(extractText(event.message.content as string | readonly { type: string; text?: string }[]), 4000) : "" }
				: { event: event.type };
		case "turn_end": {
			const usage = usageFromMessage(event.message);
			return { event: event.type, usage, toolResultCount: event.toolResults.length };
		}
		case "agent_end":
			return { event: event.type, messageCount: event.messages.length, willRetry: event.willRetry };
		case "queue_update":
			return { event: event.type, steeringCount: event.steering.length, followUpCount: event.followUp.length };
		case "compaction_end":
			return { event: event.type, reason: event.reason, aborted: event.aborted, willRetry: event.willRetry, errorMessage: event.errorMessage };
		case "auto_retry_start":
			return { event: event.type, attempt: event.attempt, maxAttempts: event.maxAttempts, delayMs: event.delayMs, errorMessage: event.errorMessage };
		case "auto_retry_end":
			return { event: event.type, success: event.success, attempt: event.attempt, finalError: event.finalError };
		case "compaction_start":
			return { event: event.type, reason: event.reason };
		case "session_info_changed":
			return { event: event.type, name: event.name };
		case "thinking_level_changed":
			return { event: event.type, level: event.level };
		default:
			return { event: event.type };
	}
}

/**
 * Tracks all agent artifacts for a harness run.
 * Stores inspectable files under .pi/harness-runs/<run-id>/ organized by sprint.
 */
export class HarnessTracker {
	readonly runDir: string;
	readonly runId: string;
	private startedAt = Date.now();
	private phaseLog: Array<{ phase: string; startedAt: number; agent: string }> = [];
	private usageRecords = new Map<string, UsageRecord>();

	constructor(cwd: string, prompt: string) {
		const slug = prompt
			.toLowerCase()
			.replace(/[^a-z0-9]+/g, "-")
			.replace(/^-|-$/g, "")
			.slice(0, 30) || "harness";
		const timestamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
		this.runId = `${timestamp}-${slug}`;
		this.runDir = join(cwd, ".pi", "harness-runs", this.runId);
		try {
			mkdirSync(this.runDir, { recursive: true });
		} catch {
			// fail silently — tracking is best-effort
		}
	}

	private write(name: string, content: string) {
		try {
			writeFileSync(join(this.runDir, name), content, "utf-8");
		} catch {
			// best-effort
		}
	}

	private writeJSON(name: string, data: unknown) {
		this.write(name, JSON.stringify(data, null, 2));
	}

	private appendNdjson(path: string, data: UnknownRecord) {
		try {
			appendFileSync(path, `${JSON.stringify({ time: new Date().toISOString(), ...data })}\n`, "utf-8");
		} catch {
			// best-effort
		}
	}

	private updateRootUsage() {
		const sessions = [...this.usageRecords.values()];
		const totals = sessions.reduce<UsageSummary>(
			(acc, item) => ({
				inputTokens: acc.inputTokens + item.inputTokens,
				outputTokens: acc.outputTokens + item.outputTokens,
				cacheReadTokens: acc.cacheReadTokens + item.cacheReadTokens,
				cacheWriteTokens: acc.cacheWriteTokens + item.cacheWriteTokens,
				thinkingTokens: acc.thinkingTokens + item.thinkingTokens,
				totalTokens: acc.totalTokens + item.totalTokens,
				totalCost: Math.round((acc.totalCost + item.totalCost) * 10000) / 10000,
				turns: acc.turns + item.turns,
			}),
			{ inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0, thinkingTokens: 0, totalTokens: 0, totalCost: 0, turns: 0 },
		);
		this.writeJSON("USAGE.json", { totals, sessions });
	}

	recordEvent(event: UnknownRecord) {
		this.appendNdjson(join(this.runDir, "EVENTS.ndjson"), event);
	}

	startPhase(phase: string, agent: string) {
		this.phaseLog.push({ phase, startedAt: Date.now(), agent });
		this.recordEvent({ event: "phase_start", phase, agent });
	}

	savePrompt(name: string, content: string) {
		try {
			const dir = join(this.runDir, "PROMPTS");
			mkdirSync(dir, { recursive: true });
			const fileName = name.endsWith(".txt") ? name : `${name}.txt`;
			writeFileSync(join(dir, fileName), content, "utf-8");
		} catch {
			// best-effort
		}
	}

	saveSystemPrompt(subDir: string, role: string, systemPrompt: string) {
		const dir = join(this.runDir, subDir);
		try {
			mkdirSync(dir, { recursive: true });
			writeFileSync(join(dir, "SYSTEM-PROMPT.txt"), systemPrompt, "utf-8");
		} catch {
			// best-effort
		}
	}

	/** Start live event logging for an agent session. Returns an unsubscribe function. */
	startEventLog(subDir: string, role: string, session: AgentSession, meta: { phase: string; agent: string }): () => void {
		const dir = join(this.runDir, subDir);
		try {
			mkdirSync(dir, { recursive: true });
		} catch {
			return () => {};
		}
		const sessionEventsPath = join(dir, "EVENTS.ndjson");
		const rootEventsPath = join(this.runDir, "EVENTS.ndjson");
		const base = { runId: this.runId, subDir, role, phase: meta.phase, agent: meta.agent };
		const writeEvent = (payload: UnknownRecord) => {
			const event = { ...base, ...payload };
			this.appendNdjson(rootEventsPath, event);
			this.appendNdjson(sessionEventsPath, event);
		};
		writeEvent({ event: "session_start" });
		return session.subscribe((event) => writeEvent(eventPayload(event)));
	}

	/** Save post-run inspectable outputs. Conversation transcripts are intentionally not written. */
	saveSession(subDir: string, role: string, session: AgentSession, systemPrompt: string) {
		const dir = join(this.runDir, subDir);
		try {
			mkdirSync(dir, { recursive: true });
		} catch {
			return;
		}

		this.saveSystemPrompt(subDir, role, systemPrompt);

		const lastText = getLastAssistantText(session);
		if (lastText) {
			writeFileSync(join(dir, "OUTPUT.md"), lastText, "utf-8");
		}

		const usage = summarizeSessionUsage(session);
		const record: UsageRecord = { id: `${subDir}/${role}`, subDir, role, ...usage };
		writeFileSync(join(dir, "USAGE.json"), JSON.stringify(record, null, 2), "utf-8");
		this.usageRecords.set(record.id, record);
		this.updateRootUsage();
	}

	/** Append a durable compact run-state ledger entry for later phases and humans. */
	appendState(heading: string, summary: string, bullets: string[] = []) {
		const statePath = join(this.runDir, "STATE.md");
		const entry = [
			`## ${heading}`,
			`Time: ${new Date().toISOString()}`,
			"",
			summary,
			bullets.length > 0 ? "" : "",
			...bullets.map((bullet) => `- ${bullet}`),
			"",
		].filter((line, index, arr) => line !== "" || arr[index - 1] !== "").join("\n");
		try {
			if (!existsSync(statePath)) writeFileSync(statePath, `# Harness Run State\n\n${entry}`, "utf-8");
			else appendFileSync(statePath, `\n${entry}`, "utf-8");
		} catch {
			// best-effort
		}
	}

	/** Read compact run-state ledger content for prompt injection. */
	readState(maxChars = 6000): string {
		try {
			const state = readFileSync(join(this.runDir, "STATE.md"), "utf-8");
			return state.length <= maxChars ? state : `${state.slice(0, Math.floor(maxChars / 2))}\n… state truncated …\n${state.slice(-Math.floor(maxChars / 2))}`;
		} catch {
			return "";
		}
	}

	/** Write the spec from the planner. */
	saveSpec(specText: string) {
		this.write("SPEC.md", specText);
	}

	/** Write final build report. */
	saveReport(report: string) {
		this.write("BUILD-REPORT.md", report);
	}

	/** Write harness workspace/isolation metadata. */
	saveWorkspace(workspace: HarnessWorkspace) {
		this.writeJSON("WORKSPACE.json", workspace);
	}

	/** Write timing summary. */
	saveTiming() {
		const elapsed = ((Date.now() - this.startedAt) / 1000).toFixed(1);
		const phases = this.phaseLog.map((p) => ({
			phase: p.phase,
			agent: p.agent,
			durationMs: Date.now() - p.startedAt,
		}));
		this.writeJSON("TIMING.json", { totalSeconds: Number(elapsed), phases, runId: this.runId, runDir: basename(this.runDir) });
	}
}
